# Generated by Django 6.0.7 on 2026-07-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("thread_id", models.CharField(blank=True, default="", max_length=255)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("mime", models.CharField(blank=True, default="", max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "file",
                    models.FileField(upload_to="django_pydantic_agent/attachments/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "-created_at"],
                        name="django_pyda_owner_i_2ab804_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "attachment_id"),
                        name="django_pydantic_agent_attachment_owner_id_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("preview", models.TextField(blank=True, default="")),
                ("messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "-updated_at"],
                        name="django_pyda_owner_i_8b93b5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "thread_id"),
                        name="django_pydantic_agent_store_owner_thread_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "conversation_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "parent_run_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "agent_name",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "started_at"],
                        name="django_pyda_owner_i_a8ce09_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "run_id"),
                        name="django_pydantic_agent_run_owner_run_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("step_index", models.IntegerField()),
                ("messages", models.JSONField(default=list)),
                (
                    "conversation_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "parent_run_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "agent_name",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "run_id"],
                        name="django_pyda_owner_i_59abe8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredStepEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("kind", models.CharField(max_length=32)),
                ("step_index", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                (
                    "conversation_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "parent_run_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "agent_name",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "tool_call_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "tool_name",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ("error", models.TextField(blank=True, default=None, null=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "run_id"],
                        name="django_pyda_owner_i_eb059a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredToolEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=255)),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("tool_call_id", models.CharField(max_length=255)),
                ("tool_name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=16)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "effect_summary",
                    models.TextField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner_id", "run_id"],
                        name="django_pyda_owner_i_b79813_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "run_id", "tool_call_id"),
                        name="django_pydantic_agent_tool_effect_owner_run_call_unique",
                    )
                ],
            },
        ),
    ]
