# Generated by Django 6.0.7 on 2026-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_pydantic_agent_store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedsnapshot",
            name="state",
            field=models.CharField(
                choices=[("complete", "complete"), ("interrupted", "interrupted")],
                default="complete",
                max_length=16,
            ),
        ),
    ]
