# Generated by Django 5.2.17 on 2026-08-12 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_pydantic_agent_store", "0002_snapshot_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="storedattachment",
            name="sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="storedattachment",
            name="file",
            field=models.FileField(db_index=True, upload_to="django_pydantic_agent/attachments/"),
        ),
        migrations.AddIndex(
            model_name="storedattachment",
            index=models.Index(
                fields=["owner_id", "sha256"], name="django_pyda_owner_i_46b43c_idx"
            ),
        ),
        migrations.AddField(
            model_name="conversationattachment",
            name="attachment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_links",
                to="django_pydantic_agent_store.storedattachment",
            ),
        ),
        migrations.AddField(
            model_name="conversationattachment",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment_links",
                to="django_pydantic_agent_store.storedconversation",
            ),
        ),
        migrations.AddField(
            model_name="storedconversation",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="conversations",
                through="django_pydantic_agent_store.ConversationAttachment",
                to="django_pydantic_agent_store.storedattachment",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationattachment",
            constraint=models.UniqueConstraint(
                fields=("conversation", "attachment"),
                name="django_pydantic_agent_conversation_attachment_unique",
            ),
        ),
    ]
