# Generated by Django 5.2.17 on 2026-08-25 10:13

from django.db import migrations, models

import django_pydantic_agent.contrib.store.storage


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_pydantic_agent_store",
            "0003_attachment_content_hash_and_conversation_links",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedattachment",
            name="file",
            field=models.FileField(
                db_index=True,
                storage=django_pydantic_agent.contrib.store.storage.attachment_storage,
                upload_to="django_pydantic_agent/attachments/",
            ),
        ),
    ]
