# Generated by Django 5.2.17 on 2026-08-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_pydantic_agent_store", "0004_alter_storedattachment_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("path", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True, default="")),
                ("version", models.CharField(max_length=32)),
                (
                    "operation_id",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "path"),
                        name="django_pydantic_agent_memory_owner_path_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredMemoryOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_id", models.CharField(blank=True, default="", max_length=255)),
                ("operation_id", models.CharField(max_length=255)),
                ("fingerprint", models.CharField(max_length=255)),
                (
                    "version",
                    models.CharField(blank=True, default=None, max_length=32, null=True),
                ),
                ("existed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "operation_id"),
                        name="django_pydantic_agent_memory_owner_operation_unique",
                    )
                ],
            },
        ),
    ]
